name: Build Binaries (Fork)
on:
  push:
    branches:
      - fork-version
  workflow_dispatch:
    inputs:
      upload-release:
        type: boolean
        description: 'Upload to GitHub Releases?'
        required: false
        default: false

permissions:
  contents: write

jobs:
  build-windows:
    name: Build Windows
    runs-on: windows-2025-vs2026
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up common secrets
        shell: bash
        run: |
          echo "${{ secrets.LOCAL_PROPERTIES }}" > local.properties

      - name: Install GraalVM CE
        uses: graalvm/setup-graalvm@v1
        with:
          version: '25'
          distribution: 'graalvm-community'
          github-token: ${{ github.token }}

      - name: Download native libraries
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          RUN_ID=$(gh run list \
            -R "kawaiiDango/pano-native-components" \
            --workflow "build.yml" \
            --status success \
            -L 1 \
            --json databaseId \
            -q '.[0].databaseId')

          if [ -z "$RUN_ID" ]; then
            echo "No successful runs found" >&2
            exit 1
          fi

          gh run download "$RUN_ID" -R "kawaiiDango/pano-native-components" -n "libs-windows-x64" -D desktopApp/resources/windows-x64

      - name: Download WebView2Loader.dll
        shell: bash
        run: |
          curl -fL -o webview2.zip "https://www.nuget.org/api/v2/package/Microsoft.Web.WebView2"
          unzip -q -o -j webview2.zip "runtimes/win-x64/native/WebView2Loader.dll" -d desktopApp/resources/windows-x64
          rm -f webview2.zip

      - name: Install Inno Setup
        shell: bash
        run: |
          winget install --id JRSoftware.InnoSetup.7 --accept-package-agreements --accept-source-agreements --disable-interactivity

      - name: Build desktop jar and native image
        shell: bash
        run: |
          ./gradlew desktopApp:packageNativeImage --no-daemon

      - name: Upload Windows exe
        uses: actions/upload-artifact@v4
        with:
          name: pano-scrobbler-windows-exe
          path: dist/*.exe

  build-linux:
    name: Build Linux
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fix permissions
        shell: bash
        run: |
          chmod +x ./gradlew

      - name: Set up common secrets
        shell: bash
        run: |
          echo "${{ secrets.LOCAL_PROPERTIES }}" > local.properties

      - name: Install GraalVM CE
        uses: graalvm/setup-graalvm@v1
        with:
          version: '25'
          distribution: 'graalvm-community'
          github-token: ${{ github.token }}

      - name: Download native libraries
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          RUN_ID=$(gh run list \
            -R "kawaiiDango/pano-native-components" \
            --workflow "build.yml" \
            --status success \
            -L 1 \
            --json databaseId \
            -q '.[0].databaseId')

          if [ -z "$RUN_ID" ]; then
            echo "No successful runs found" >&2
            exit 1
          fi

          gh run download "$RUN_ID" -R "kawaiiDango/pano-native-components" -n "libs-linux-x64" -D desktopApp/resources/linux-x64

      - name: Download AppImageTool
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          arch=$(uname -m)
          appImageToolFile="$HOME/appimagetool-$arch.AppImage"
          gh release download continuous \
            --repo AppImage/appimagetool \
            --pattern "appimagetool-$arch.AppImage" \
            --output "$appImageToolFile"
          chmod +x "$appImageToolFile"

      - name: Set up Flatpak
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y flatpak
          flatpak remote-add --user --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
          flatpak install --user -y flathub org.gnome.Platform//47 org.gnome.Sdk//47

      - name: Build desktop jar and native image
        shell: bash
        run: |
          ./gradlew desktopApp:packageNativeImage --no-daemon

      - name: Upload Linux AppImage
        uses: actions/upload-artifact@v4
        with:
          name: pano-scrobbler-linux-appimage
          path: dist/*.AppImage

      - name: Upload Linux Flatpak
        uses: actions/upload-artifact@v4
        with:
          name: pano-scrobbler-linux-flatpak
          path: dist/*.flatpak

  build-android:
    name: Build Android
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fix permissions
        shell: bash
        run: |
          chmod +x ./gradlew

      - name: Set up common secrets
        shell: bash
        run: |
          echo "${{ secrets.LOCAL_PROPERTIES }}" > local.properties

      - name: Set up Android secrets
        shell: bash
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE_JKS }}" | base64 -d - > androidApp/android-keystore.jks

      - name: Update Android package name to org.blackspectrum.scrobbler
        shell: bash
        run: |
          sed -i 's/set("APP_ID", "com.arn.scrobble")/set("APP_ID", "org.blackspectrum.scrobbler")/g' build.gradle.kts

      - name: Build APK
        shell: bash
        run: |
          export JAVA_HOME=$JAVA_HOME_25_X64
          $ANDROID_HOME/cmdline-tools/**/bin/sdkmanager --update
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --list_installed
          ./gradlew androidApp:assembleReleaseGithub --no-daemon
          mkdir -p dist
          find androidApp/build/outputs/apk/ -type f -name "*.apk" -exec cp -v {} dist/pano-scrobbler-android-universal.apk \;
          ls -la dist/

      - name: Upload Android APK
        uses: actions/upload-artifact@v4
        with:
          name: pano-scrobbler-android-universal
          path: dist/*.apk

  release:
    name: Release
    needs: [ build-windows, build-linux, build-android ]
    if: inputs.upload-release
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist-release
          merge-multiple: true

      - name: Read version
        id: release_metadata
        shell: bash
        run: |
          verCode=$(cat version.txt | tr -d '[:space:]')
          verName="$((verCode / 100)).$((verCode % 100))"
          echo "verCode=$verCode" >> $GITHUB_OUTPUT
          echo "verName=$verName" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ steps.release_metadata.outputs.verCode }}
          target_commitish: ${{ github.sha }}
          name: ${{ steps.release_metadata.outputs.verName }}
          draft: false
          prerelease: false
          files: dist-release/*
